### PR TITLE
Authenticate connections to the admin socket channel

### PR DESCRIPTION
**Pull request by mlinderm**
Restricts connections to a room's administration channel (the "console") to authenticated users recorded as an administrator for a room. Uses NextAuth JWT session data during socket connection to accept/reject the connection. Currently there is no feedback to the user when a connection is rejected. As part of this change, split the different views back into separate pages and switched to server-side rendering.

### CODE REVIEW

**Comment by KatieMacalintal** [comment]
I think the code looks good! 
Quick question about the current behavior: when I ran this after authenticating myself, I was able to access the console to the pre-existing rooms I didn’t create like CS312F23 or CS150F23. Is that that the current expected behavior since those rooms were pre-existing?

**Comment by mlinderm** [comment]
I realize it is not connecting to the socket, but still creating the socket object and rendering the page (you just can't do anything...). I think I need to add functionality to determine the state of the socket, so we only render the page if you can actually connect.

**Comment by KatieMacalintal** [comment]
Looks like it's working as expected!!

On a side note, this PR shouldn't affect the ability to create a new room using the `/rooms/new` path right? When I tried making a new room on this branch, I was never redirected to it and didn't it listed under the `/rooms` page after clicking the Create button. I ended up checking out to main, creating a new room, and then checking out to this branch to make sure I could access the console to that newly created room.

**Comment by mlinderm** [comment]
Thanks for catching that. I had deleted a line in the server that thought was not needed, and clearly it was... but not in a way that is caught by the tests.

**Review by KatieMacalintal — APPROVED** [review]

**Pull request merged**
